# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ai-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=your_openai_or_groq_key
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ai_chat
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
